margin = 92
indent = 4
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
always_use_return = true
whitespace_in_kwargs = true
normalize_line_endings = "unix"
verbose = true
trailing_comma = "nothing"

