margin = 92
indent = 4
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = false
remove_extra_newlines = false
always_use_return = false
whitespace_in_kwargs = false
normalize_line_endings = "unix"
verbose = true
trailing_comma = "nothing"
