name: Documentation Build and Deploy

on:
  push:
    branches:
      - docs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.5

      - run: touch page/__site/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: docs/
