name: Gh Page Update

on:
  push:
    branches:
      - docs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git add
        run: git add docs

      - name: Git commit
        run: git commit -m "Publish HTML files"

      - name: Push build to branch
        run: |
          git push origin gh-pages